"use strict";
var assert = require("assert");
var path = require("path");
global.window = global;
global.Image = function () { this.complete = false; this.naturalWidth = 0; };
global.localStorage = { getItem: function () { return null; }, setItem: function () {} };
var root = path.resolve(__dirname, "..");
["config", "collision", "entities", "map", "ai", "effects"].forEach(function (name) { require(path.join(root, "js", name + ".js")); });
TankGame.Audio = { play: function () {}, playBurning: function () { return {}; }, stopBurningSound: function () {} };
require(path.join(root, "js", "game.js"));
var canvas = { width: 1440, height: 900, getContext: function () { return {}; } };
var input = { pointer: { down: false, pressed: false, inside: false }, isDown: function () { return false; }, reset: function () {}, setCamera: function () {} };
var game = new TankGame.Game(canvas, input);
game.setMode("brave");
game.start();
game.state = TankGame.Config.states.PLAYING;
assert.strictEqual(game.worldMap.isBossMap, true);
assert.ok(game.worldMap.firePatches.length > 0);
var tank = TankGame.Entities.createTank(game.worldMap.firePatches[0].x, game.worldMap.firePatches[0].y, "enemy");
tank.health = 20; tank.maxHealth = 20;
game.enemies = [tank];
game.updateFireHazards(0.1);
assert.strictEqual(tank.burning, true);
assert.strictEqual(tank.health, 20);
game.updateFireHazards(0.4);
assert.strictEqual(tank.health, 18);
game.updateFireHazards(0.1);
assert.strictEqual(tank.health, 18);
tank.x += 400;
game.updateFireHazards(2.9);
assert.strictEqual(tank.burning, true);
assert.strictEqual(tank.health, 6, "burn damage continues after leaving the fire");
game.updateFireHazards(0.1);
assert.strictEqual(tank.burning, false);
assert.strictEqual(TankGame.Entities.chooseTurretWeapon(0.09), "bullet");
assert.strictEqual(TankGame.Entities.chooseTurretWeapon(0.1), "bomb");
assert.strictEqual(TankGame.Entities.chooseTurretWeapon(0.59), "bomb");
assert.strictEqual(TankGame.Entities.chooseTurretWeapon(0.6), "mortar");
console.log("Boss fire and turret probability tests: PASS");